name: Linux Build (x86_64 + ARM64)

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Linux x86_64 and ARM64 builds'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["x86_64", "arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.12.0 -r src/requirements.txt

      - name: Install QEMU (for ARM64 cross-build)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binutils-aarch64-linux-gnu binfmt-support build-essential python3-dev
          sudo update-binfmts --enable qemu-aarch64 || echo "binfmt-support already enabled or not needed"
      
      - name: Build with PyInstaller (${{ matrix.arch }})
        run: |
          cd src
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            qemu-aarch64-static pyinstaller QtTinySA.spec
          else
            pyinstaller QtTinySA.spec
          fi
          mv dist/QtTinySA dist/QtTinySA_${{ matrix.arch }}
          cd ..

      - name: Verify binary architecture (${{ matrix.arch }})
        run: |
          file src/dist/QtTinySA

      - name: Upload artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: QtTinySA_linux_${{ matrix.arch }}
          path: src/dist/QtTinySA_${{ matrix.arch }}
          if-no-files-found: error